### ISSUE TITLE
Bootstrap.sh not working

### ISSUE THREAD

**Issue by vooop-binary** [josepmdc/dotfiles#1]
```
bootstrap.sh: 36: Syntax error: "(" unexpected (expecting "then")
```
happening right after the i3 question

**Comment by josepmdc** [comment]
Thanks, I'll try to fix it tomorrow, I didn't quite test that part yet, my bad🙃

**Comment by vooop-binary** [comment]
> 
> 
> Thanks, I'll try to fix it tomorrow, I didn't quite test that part yet, my bad🙃

thx

**Comment by josepmdc** [comment]
@vooop-binary I can't reproduce the error, it works for me. I added some modifications to the script but I don't think they have anything to do with your error. What version of bash are you using?

**Comment by vooop-binary** [comment]
> 
> 
> @vooop-binary I can't reproduce the error, it works for me. I added some modifications to the script but I don't think they have anything to do with your error. What version of bash are you using?

i'm using zsh(5.8) actually should I use bash(5.0.17)?

**Comment by josepmdc** [comment]
Hmm, that could be the problem, because it's a bash script. But I also use zsh and it works for me 🤔.

**Comment by josepmdc** [comment]
I pushed some changes that should make it compatible with other shells, maybe now it works.

**Comment by vooop-binary** [comment]
> I pushed some changes that should make it compatible with other shells, maybe now it works.

thx it works
